platform :android do
  desc "Upload a new Android version to the Google Play Store"
  lane :internal do
    upload_to_play_store(track: 'internal',release_status: 'completed',aab: "#{ENV['ANDROID_BUILD_FILE_PATH']}")
    qa_publish(webhook_url: 'https://discord.com/api/webhooks/785154510417952788/CHxgMU5ijlgbvPsYXHgE4f0-2zRSvGUjKjXxbw8Cl15P--uBGrmTJ9SaxDt1X2JusEZq', webhook_body: '{"content":"<@&813477342101897246> Released new version on the internal track","embeds":null}')
  end
end
