// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: my.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace pandora.messages
{

    [global::ProtoBuf.ProtoContract()]
    public partial class Spawn : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"unit_name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string UnitName { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"x")]
        public int X { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"y")]
        public int Y { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Join : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"token")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Token { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ClientEnvelope : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(3, Name = @"token")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Token { get; set; } = "";

        [global::ProtoBuf.ProtoMember(1, Name = @"spawn")]
        public Spawn Spawn
        {
            get { return __pbn__message.Is(1) ? ((Spawn)__pbn__message.Object) : default; }
            set { __pbn__message = new global::ProtoBuf.DiscriminatedUnionObject(1, value); }
        }
        public bool ShouldSerializeSpawn() => __pbn__message.Is(1);
        public void ResetSpawn() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__message, 1);

        private global::ProtoBuf.DiscriminatedUnionObject __pbn__message;

        [global::ProtoBuf.ProtoMember(2, Name = @"join")]
        public Join Join
        {
            get { return __pbn__message.Is(2) ? ((Join)__pbn__message.Object) : default; }
            set { __pbn__message = new global::ProtoBuf.DiscriminatedUnionObject(2, value); }
        }
        public bool ShouldSerializeJoin() => __pbn__message.Is(2);
        public void ResetJoin() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__message, 2);

        public MessageOneofCase MessageCase => (MessageOneofCase)__pbn__message.Discriminator;

        public enum MessageOneofCase
        {
            None = 0,
            Spawn = 1,
            Join = 2,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ServerEnvelope : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"start")]
        public Start Start
        {
            get { return __pbn__message.Is(1) ? ((Start)__pbn__message.Object) : default; }
            set { __pbn__message = new global::ProtoBuf.DiscriminatedUnionObject(1, value); }
        }
        public bool ShouldSerializeStart() => __pbn__message.Is(1);
        public void ResetStart() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__message, 1);

        private global::ProtoBuf.DiscriminatedUnionObject __pbn__message;

        [global::ProtoBuf.ProtoMember(2, Name = @"spawn")]
        public Spawn Spawn
        {
            get { return __pbn__message.Is(2) ? ((Spawn)__pbn__message.Object) : default; }
            set { __pbn__message = new global::ProtoBuf.DiscriminatedUnionObject(2, value); }
        }
        public bool ShouldSerializeSpawn() => __pbn__message.Is(2);
        public void ResetSpawn() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__message, 2);

        public MessageOneofCase MessageCase => (MessageOneofCase)__pbn__message.Discriminator;

        public enum MessageOneofCase
        {
            None = 0,
            Start = 1,
            Spawn = 2,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Start : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
